#include <tamtypes.h>
#include <kernel.h>
#include <sifrpc.h>
#include <loadfile.h>
#include <iopcontrol.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "gfx.h"
#include "utils.h"

// Embedded IRX files (generated by bin2c in Makefile)
extern u8 ps2atad_irx[];
extern u32 size_ps2atad_irx;

extern u8 ps2hdd_irx[];
extern u32 size_ps2hdd_irx;

extern u8 ps2fs_irx[];
extern u32 size_ps2fs_irx;

extern u8 usbd_irx[];
extern u32 size_usbd_irx;

extern u8 usbhdfsd_irx[];
extern u32 size_usbhdfsd_irx;

void gfx_error(const char *msg) {
    while (1) {
        gfx_flip();
        gfx_clear(GS_SETREG_RGBAQ(0x00, 0x00, 0x00, 0x00, 0x00));
        gfx_draw_text(msg, 10, 50, GS_SETREG_RGBAQ(0xFF, 0x00, 0x00, 0x80, 0x00), 1, 2);
        gfx_exec();
    }
}

void init(void) {
    SifInitRpc(0);
    while (!SifIopReset("", 0)) {};
    while (!SifIopSync()) {};
    SifInitRpc(0);

    // Memory Card modules (always load first)
    SifLoadModule("rom0:MCMAN", 0, NULL);
    SifLoadModule("rom0:MCSERV", 0, NULL);

    // USB modules - using embedded files
    int ret = SifExecModuleBuffer(usbd_irx, size_usbd_irx, 0, NULL, NULL);
    if (ret < 0) {
        // Try fallback to rom0:USBD if embedded fails
        ret = SifLoadModule("rom0:USBD", 0, NULL);
        if (ret < 0) gfx_error("USBD LOAD FAILED");
    }

    ret = SifExecModuleBuffer(usbhdfsd_irx, size_usbhdfsd_irx, 0, NULL, NULL);
    if (ret < 0) gfx_error("USBHDFSD LOAD FAILED");

    // HDD modules - critical chain
    ret = SifExecModuleBuffer(ps2atad_irx, size_ps2atad_irx, 0, NULL, NULL);
    if (ret < 0) gfx_error("PS2ATAD LOAD FAILED");

    char hdd_args[] = "-o\0" "4\0" "-n\0" "20";
    ret = SifExecModuleBuffer(ps2hdd_irx, size_ps2hdd_irx, sizeof(hdd_args), hdd_args, NULL);
    if (ret < 0) gfx_error("PS2HDD LOAD FAILED");

    ret = SifExecModuleBuffer(ps2fs_irx, size_ps2fs_irx, 0, NULL, NULL);
    if (ret < 0) gfx_error("PS2FS LOAD FAILED");

    // Small delay for drivers to settle
    FuckAroundSilentlyMs(2000);

    // Initialize graphics
    gfx_init();
    gfx_flip();
    gfx_clear(GS_SETREG_RGBAQ(0x00, 0x00, 0x00, 0x00, 0x00));
    gfx_exec();
}

// Check if HDD partition exists
int hdd_partition_exists(const char *partition_name) {
    char fullpath[64];
    snprintf(fullpath, sizeof(fullpath), "hdd0:%s", partition_name);

    int fd = open(fullpath, O_RDONLY);
    if (fd >= 0) {
        close(fd);
        return 1;
    }
    return 0;
}

// Simple file existence check
int file_exists(const char *filename) {
    FILE *f = fopen(filename, "r");
    if (f) {
        fclose(f);
        return 1;
    }
    return 0;
}

int main(void) {
    init();

    FuckAroundSilentlyMs(4000);

    // === HDD ===
    if (hdd_partition_exists("__freebbn")) {
        int file_found = file_exists("pfs0:freebbn.elf") ||
                         file_exists("pfs0:/freebbn.elf");

        while (1) {
            gfx_flip();
            gfx_clear(GS_SETREG_RGBAQ(0x00, 0x00, 0x00, 0x00, 0x00));
            if (file_found) {
                gfx_draw_text("HDD FOUND + FILE", 10, 50,
                              GS_SETREG_RGBAQ(0x00, 0xFF, 0x00, 0x80, 0x00), 1, 2);
            } else {
                gfx_draw_text("HDD PARTITION FOUND", 10, 50,
                              GS_SETREG_RGBAQ(0x00, 0xFF, 0x80, 0x80, 0x00), 1, 2);
            }
            gfx_exec();
        }
    }

    FuckAroundSilentlyMs(3000);

    // === MC0 ===
    if (file_exists("mc0:/freebbn/freebbn.elf") ||
        file_exists("mc0:freebbn/freebbn.elf")) {
        while (1) {
            gfx_flip();
            gfx_clear(GS_SETREG_RGBAQ(0x00, 0x00, 0x00, 0x00, 0x00));
            gfx_draw_text("MC0 FOUND", 10, 50,
                          GS_SETREG_RGBAQ(0xFF, 0xFF, 0x00, 0x80, 0x00), 1, 2);
            gfx_exec();
        }
    }

    FuckAroundSilentlyMs(3000);

    // === MC1 ===
    if (file_exists("mc1:/freebbn/freebbn.elf") ||
        file_exists("mc1:freebbn/freebbn.elf")) {
        while (1) {
            gfx_flip();
            gfx_clear(GS_SETREG_RGBAQ(0x00, 0x00, 0x00, 0x00, 0x00));
            gfx_draw_text("MC1 FOUND", 10, 50,
                          GS_SETREG_RGBAQ(0xFF, 0xFF, 0x00, 0x80, 0x00), 1, 2);
            gfx_exec();
        }
    }

    FuckAroundSilentlyMs(3000);

    // === USB MASS (for slims) ===
    if (file_exists("mass:/freebbn.elf") ||
        file_exists("mass:freebbn.elf")) {
        while (1) {
            gfx_flip();
            gfx_clear(GS_SETREG_RGBAQ(0x00, 0x00, 0x00, 0x00, 0x00));
            gfx_draw_text("USB MASS FOUND", 10, 50,
                          GS_SETREG_RGBAQ(0x00, 0xFF, 0xFF, 0x80, 0x00), 1, 2);
            gfx_exec();
        }
    }

    // === Fallback ===
    while (1) {
        gfx_flip();
        gfx_clear(GS_SETREG_RGBAQ(0x00, 0x00, 0x00, 0x00, 0x00));
        gfx_draw_text("NOTHING FOUND", 10, 50,
                      GS_SETREG_RGBAQ(0xFF, 0x00, 0x00, 0x80, 0x00), 1, 2);
        gfx_exec();
    }

    return 0;
}
